name: "Pocket ID"
version: "1.0.0"
slug: "pocket-id"
description: "Simple OIDC provider for passkey authentication"
url: "https://github.com/quintenbuwalda/hass-addons/tree/main/pocket-id"
arch:
  - aarch64
  - amd64
init: false
options: {}
schema: {}
